version: "3.3"
services:
  shelter_db:
    image: postgres:15.5
    volumes:
      - './docker/database:/var/lib/postgresql/data'
    env_file:
      - ./backend/.env
    networks:
      - web

  backend:
    container_name: backend
    command: python3 /backend/main.py
    depends_on:
      - shelter_db
    build:
      context: ../
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ../animal_photos:/animal_photos
    env_file:
      - ./backend/.env
    networks:
      - web

  nginx:
    image: nginx
    hostname: nginx-entrypoint
    restart: unless-stopped
    container_name: nginx-entrypoint
    depends_on:
      - shelter_db
      - backend
    environment:
      TZ: "Europe/Moscow"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/ssl:/etc/nginx/ssl
      - ./well-known:/usr/share/nginx/html
      - ./certs:/etc/letsencrypt
      - ../animal_photos:/download/photo/
    networks:
      - web

networks:
    web:
      driver: bridge
      attachable: true
      ipam:
        driver: default
        config:
          - subnet: 162.28.0.0/16