version: "3.3"
services:
  backend:
    container_name: backend
    command: python3 main.py
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file:
      - ./settings/.local.env

  psql:
    image: postgres
    environment:
      POSTGRES_DB: "shelterpaws-testing-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - './docker/database:/var/lib/psql'
    ports:
      - "5432:5432"
